version: "3"
name: order-service-test

services:
  order-service-api:
    container_name: order-service-api
    build:
      context: .
      dockerfile: src/api/Api/Dockerfile
    pull_policy: always
    restart: always
    ports:
      - "5003:5003"
    networks:
      - main
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5002
      INITIAL_CATALOG: OrderServiceProd
      GITHUB_USERNAME: ""
      GITHUB_TOKEN: ""
  order-service-web:
    container_name: order-service-web
    build:
      context: src/web
      dockerfile: Dockerfile
    pull_policy: always
    restart: always
    ports:
      - "3003:80"
    networks:
      - main
    environment:
      GITHUB_TOKEN: ""
networks:
  main:
    name: main
    driver: bridge
    external: true
