name: emissor-digital-os

services:
  api:
    container_name: emissor-digital-os-api
    build:
      context: .
      dockerfile: src/api/Api/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    pull_policy: always
    restart: always
    ports:
      - "5002:5002"
    networks:
      - main
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5002
      INITIAL_CATALOG: OrderServiceProd
  web:
    container_name: emissor-digital-os-web
    build:
      context: src/web
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    pull_policy: always
    restart: always
    ports:
      - "3000:80"
    networks:
      - main
networks:
  main:
    name: main
    driver: bridge
    external: true
