name: Build and publish emissor digital de os api

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - master

jobs:
  build-and-publish-emissor-digital-api:
    if: (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master') || (github.event_name == 'push' && github.ref == 'refs/heads/master')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build the Docker image
        run: docker build . -t ghcr.io/vinicios-campera/order-service-api:latest -f src/api/Api/Dockerfile

      - name: Push the Docker image
        run: docker push ghcr.io/vinicios-campera/order-service-api:latest
