name: Build and publish emissor digital de os web

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - master

jobs:
  build-and-publish-emissor-digital-web:
    if: (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master') || (github.event_name == 'push' && github.ref == 'refs/heads/master')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build the Docker image
        run: |
          cd src/web
          docker build . -t ghcr.io/vinicios-campera/order-service-web:latest

      - name: Push the Docker image
        run: docker push ghcr.io/vinicios-campera/order-service-web:latest
